FROM ubuntu:18.04 as common

RUN apt-get update --fix-missing \
  && apt-get install -y curl unzip

ARG lumavate_exceptions_branch=master
ARG lumavate_signer_branch=master
ARG lumavate_token_branch=master
ARG lumavate_request_branch=master
ARG lumavate_properties_branch=master
ARG lumavate_service_util_branch=develop

RUN curl -LOk https://github.com/LabelNexus/python-exceptions/archive/master.zip \
      && unzip master.zip -d /python_packages \
      && rm master.zip \
      && cd /python_packages \
      && mv ./python-exceptions-master ./lumavate_exceptions \
      && cd ../

RUN curl -LOk https://github.com/Lumavate-Team/python-service-util/archive/master.zip \
      && unzip master.zip -d /python_packages \
      && rm master.zip \
      && cd /python_packages \
      && mv ./python-service-util-master ./lumavate_service_util \
      && cd ../

RUN curl -LOk https://github.com/Lumavate-Team/python-signer/archive/master.zip \
      && unzip master.zip -d /python_packages \
      && rm master.zip \
      && cd /python_packages \
      && mv ./python-signer-master ./lumavate_signer \
      && cd ../

RUN curl -LOk https://github.com/LabelNexus/python-token/archive/master.zip \
      && unzip master.zip -d /python_packages \
      && rm master.zip \
      && cd /python_packages \
      && mv ./python-token-master ./lumavate_token \
      && cd ../

RUN curl -LOk https://github.com/LabelNexus/python-api-request/archive/master.zip \
      && unzip master.zip -d /python_packages \
      && rm master.zip \
      && cd /python_packages \
      && mv ./python-api-request-master ./lumavate_request \
      && cd ../

RUN curl -LOk https://github.com/LabelNexus/python-widget-properties/archive/master.zip \
      && unzip master.zip -d /python_packages \
      && rm master.zip \
      && cd /python_packages \
      && mv ./python-widget-properties-master ./lumavate_properties \
      && cd ../

FROM python:3.7-alpine3.9

COPY --from=common /python_packages ./python_packages/
COPY requirements.txt ./

EXPOSE 5000

RUN apk add --no-cache \
    postgresql-libs \
  && apk add --no-cache --virtual .build-deps \
    gcc \
    libc-dev \
    libgcc \
    linux-headers \
    libffi-dev \
    libressl-dev \
    musl-dev \
    postgresql-dev \
  && pip3 install -r requirements.txt \
  && mkdir -p /app \
  && apk del .build-deps

ENV PYTHONPATH /python_packages
WORKDIR /app
COPY ./app /app

CMD gunicorn app:app -b 0.0.0.0:5000 --workers 4 --worker-class eventlet
